export const IAB_CATEGORIES = [
  { id: "IAB1", name: "Arts & Entertainment", color: "#F94144" },
  { id: "IAB2", name: "Automotive", color: "#F3722C" },
  { id: "IAB3", name: "Business", color: "#F9C74F" },
  { id: "IAB4", name: "Careers", color: "#90BE6D" },
  { id: "IAB5", name: "Education", color: "#43AA8B" },
  { id: "IAB6", name: "Family & Parenting", color: "#577590" },
  { id: "IAB7", name: "Health & Fitness", color: "#277DA1" },
  { id: "IAB8", name: "Food & Drink", color: "#4D908E" },
  { id: "IAB9", name: "Hobbies & Interests", color: "#F8961E" },
  { id: "IAB10", name: "Home & Garden", color: "#F9844A" },
  { id: "IAB11", name: "Law, Gov’t & Politics", color: "#F9844A"  },
  { id: "IAB12", name: "News", color: "#F9844A"  },
  { id: "IAB13", name: "Personal Finance", color: "#F9844A"  },
  { id: "IAB14", name: "Society", color: "#F9844A"  },
  { id: "IAB15", name: "Science", color: "#F9844A"  },
  { id: "IAB16", name: "Pets", color: "#F9844A"  },
  { id: "IAB17", name: "Sports", color: "#F9844A"  },
  { id: "IAB18", name: "Style & Fashion", color: "#F9844A"  },
  { id: "IAB19", name: "Technology & Computing", color: "#F9844A"  },
  { id: "IAB20", name: "Travel", color: "#F9844A"  },
  { id: "IAB21", name: "Real Estate", color: "#F9844A"  },
  { id: "IAB22", name: "Shopping", color: "#F9844A"  },
  { id: "IAB23", name: "Religion & Spirituality", color: "#F9844A"  },
  { id: "IAB24", name: "Uncategorized", color: "#F9844A"  },
];
